---

- debug:
    msg: "Confluent Platform requires your agreement to a usage license. Please download ZIP release at http://www.confluent.io/download and place the file at the project root (expected file name: confluent-3.0.0-2.11.zip)"



# python-pip, docker, docker-py

- name: Start Zookeeper
  docker_container:
    name: zookeeper
    image: confluent/zookeeper
    state: started
    ports:
     - "2181:2181"
  become: yes
  become_method: sudo

- name: Waiting for Zookeeper to start
  wait_for: port=2181

- name: Start Kafka Broker
  docker_container:
    name: kafka
    image: confluent/kafka
    state: started
    links:
     - "zookeeper:zookeeper"
    ports:
     - "9092:9092"
  become: yes
  become_method: sudo

- name: Waiting for Kafka to start
  wait_for: port=9092

- name: Start Schema Registry
  docker_container:
    name: schema-registry
    image: confluent/schema-registry
    state: started
    links:
     - "zookeeper:zookeeper"
     - "kafka:kafka"
    ports:
     - "8081:8081"
  become: yes
  become_method: sudo

- name: Waiting for Schema Registry to start
  wait_for: port=8081

- name: Start Connect
  docker_container:
    name: connect
    image: ftrossbach/kafka-connect
    state: started
    links:
     - "zookeeper:zookeeper"
     - "kafka:kafka"
    ports:
     - "8083:8083"
  become: yes
  become_method: sudo

- name: Waiting for Connect to start
  wait_for: port=8083

- name: Start Control-Center
  docker_container:
    name: control-center
    image: ftrossbach/confluent-control-center
    state: started
    links:
     - "zookeeper:zookeeper"
     - "kafka:kafka"
     - "connect:connect"
    ports:
     - "9021:9021"
  become: yes
  become_method: sudo

- name: Waiting for Control Center to start
  wait_for: port=9021