---

- debug:
    msg: "Confluent Platform requires your agreement to a usage license. Please download ZIP release at http://www.confluent.io/download and place the file at the project root (expected file name: confluent-3.0.0-2.11.zip)"

- name: Install Java Runtime
  apt: name=openjdk-8-jre state=present update_cache=yes
  become: yes
  become_method: sudo

- name: Install daemon
  apt: name=daemon state=present
  become: yes
  become_method: sudo

- name: Copy confluent platform
  copy: src=../confluent-3.0.0-2.11.zip dest=/home/vagrant/confluent.zip

- name: Unzip confluent platform
  unarchive: src=/home/vagrant/confluent.zip dest=/home/vagrant/ copy=no

- name: Start Zookeeper
  shell: daemon -- /home/vagrant/confluent-3.0.0/bin/zookeeper-server-start  /home/vagrant/confluent-3.0.0/etc/kafka/zookeeper.properties
  ignore_errors: yes


- name: Waiting for Zookeeper to start
  wait_for: port=2181

- name: Start Kafka Broker
  shell: daemon -- /home/vagrant/confluent-3.0.0/bin/kafka-server-start  /home/vagrant/confluent-3.0.0/etc/kafka/server.properties
  ignore_errors: yes

- name: Waiting for Kafka to start
  wait_for: port=9092

- name: Start Schema Registry
  shell: daemon -- /home/vagrant/confluent-3.0.0/bin/schema-registry-start  /home/vagrant/confluent-3.0.0/etc/schema-registry/schema-registry.properties
  ignore_errors: yes

- name: Waiting for Schema Registry to start
  wait_for: port=8081

- name: Copy Kafka Connect configuration
  copy: src=connect.properties dest=/home/vagrant/connect.properties

- name: Start Kafka Connect
  shell: daemon -- /home/vagrant/confluent-3.0.0/bin/connect-distributed  /home/vagrant/connect.properties

- name: Waiting for Kafka Connect to start
  wait_for: port=8083

- name: Copy Control Center configuration
  copy: src=control-center.properties dest=/home/vagrant/control-center.properties

- name: Start Control Center
  shell: daemon -- /home/vagrant/confluent-3.0.0/bin/control-center-start  /home/vagrant/control-center.properties
  ignore_errors: yes

- name: Waiting for Control Center to start
  wait_for: port=9021